"""OrderShareToken model (ADR-0036 §2.3, PRD-001 v1.2 §4).

Single-order scoped share token for the W20 Top1 family companion view.
The token serves as the URL handle inside the short link
``https://m.yiluan.cn/s/{token}`` and is later exchanged (after silent
WeChat openid auth or SMS OTP fallback) for a ``share_session`` JWT
(TTL 30min) that powers the REST + WS read-only family view.

Design notes
------------
* Tokens are URL-safe random strings (length 32). Uniqueness enforced at
  the DB layer to defend against token-prediction attacks.
* Each order has at most 3 active (unexpired + non-revoked) tokens; the
  repository helper ``ensure_active_token_cap`` auto-revokes the oldest
  active token before inserting the new one.
* Tokens are NOT renewable. Once expired, callers must request a fresh
  one — keeps audit trails clean.
* ``expires_at`` defaults to ``order.completed_at + 24h``; the helper
  ``compute_expires_at`` enforces a hard cap of ``created_at + 7d`` for
  pre-completion shares.
* Access metadata is aggregated on the same row to avoid an additional
  hot write per visit. ``distinct_accessor_count`` > 5 within a 24h
  rolling window triggers an automatic revoke + alert (handled by
  ``S2-DEV-006`` scanner).
"""

from __future__ import annotations

import enum
import secrets
import uuid
from datetime import datetime, timedelta, timezone

from sqlalchemy import (
    DateTime,
    Enum as SAEnum,
    ForeignKey,
    Index,
    Integer,
    String,
    UniqueConstraint,
    Uuid,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


# Token defaults --------------------------------------------------------------

TOKEN_LENGTH_CHARS = 32  # URL-safe base64ish length
ACTIVE_TOKEN_CAP_PER_ORDER = 3
DEFAULT_EXPIRES_AFTER_COMPLETION = timedelta(hours=24)
HARD_CAP_EXPIRES_AFTER_CREATION = timedelta(days=7)


class ShareScope(str, enum.Enum):
    """Slice of order data visible to family viewers."""

    FULL = "full"
    PROGRESS_ONLY = "progress_only"


def generate_token() -> str:
    """Generate a URL-safe random token of fixed length."""
    # ``token_urlsafe`` returns ~4/3 chars per byte; trim to fixed length.
    raw = secrets.token_urlsafe(48)
    return raw[:TOKEN_LENGTH_CHARS]


def compute_expires_at(
    *,
    created_at: datetime,
    order_completed_at: datetime | None,
) -> datetime:
    """Compute the share token expiry per ADR-0036 §2.3 policy.

    - Pre-completion: ``created_at + 24h``, capped at ``created_at + 7d``.
    - Post-completion: ``order.completed_at + 24h``, also capped at
      ``created_at + 7d``.
    """
    hard_cap = created_at + HARD_CAP_EXPIRES_AFTER_CREATION
    if order_completed_at is None:
        candidate = created_at + DEFAULT_EXPIRES_AFTER_COMPLETION
    else:
        candidate = order_completed_at + DEFAULT_EXPIRES_AFTER_COMPLETION
    return min(candidate, hard_cap)


class OrderShareToken(Base):
    """One row per share link generated by the order owner."""

    __tablename__ = "order_share_tokens"
    __table_args__ = (
        UniqueConstraint("token", name="uq_order_share_tokens_token"),
        Index("ix_order_share_tokens_order_id", "order_id"),
        Index("ix_order_share_tokens_created_by", "created_by"),
        Index("ix_order_share_tokens_expires_at", "expires_at"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    order_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("orders.id", ondelete="CASCADE"),
        nullable=False,
    )
    created_by: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )
    token: Mapped[str] = mapped_column(
        String(64), nullable=False, default=generate_token
    )
    share_scope: Mapped[ShareScope] = mapped_column(
        SAEnum(ShareScope, name="share_scope_enum", native_enum=False, length=16),
        nullable=False,
        default=ShareScope.FULL,
    )
    expires_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    revoked_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    revoked_by: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), nullable=True
    )

    # Access aggregates (no per-visit row to keep writes cheap).
    first_accessed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    first_accessor_openid: Mapped[str | None] = mapped_column(
        String(64), nullable=True
    )
    distinct_accessor_count: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0
    )
    last_accessed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    # Convenience -----------------------------------------------------------

    @property
    def is_active(self) -> bool:
        """A token is active iff it is not revoked and not yet expired."""
        if self.revoked_at is not None:
            return False
        exp = self.expires_at
        if exp.tzinfo is None:
            # SQLite drops tz info; assume UTC for comparison purposes.
            exp = exp.replace(tzinfo=timezone.utc)
        return exp > datetime.now(timezone.utc)
