"""Admin companion certification-image local storage + signed access.

S2-DEV-013 PR-E2 Phase A (ADR-0044): MVP local/private storage.
Phase B will replace this with OSS/Azure/S3 native signed URLs.
"""

from __future__ import annotations

import hashlib
import hmac
import mimetypes
import time
import uuid
from pathlib import Path

from fastapi import UploadFile

from app.config import settings
from app.exceptions import (
    BadRequestException,
    ForbiddenException,
    NotFoundException,
    PayloadTooLargeException,
    UnsupportedMediaTypeException,
)

ALLOWED_CERT_IMAGE_TYPES = {
    "image/jpeg": ".jpg",
    "image/jpg": ".jpg",
    "image/png": ".png",
    "image/webp": ".webp",
}
MAX_CERT_IMAGE_SIZE = 5 * 1024 * 1024  # 5MB
SIGNED_URL_TTL_SECONDS = 15 * 60
CERT_IMAGE_DIR = Path(__file__).parent.parent.parent / "private" / "certification-images"
CERT_IMAGE_PREFIX = "cert-image://"


def _secret() -> bytes:
    return settings.jwt_secret_key.encode("utf-8")


def _safe_filename(filename: str) -> str:
    """Accept only files generated by this service."""
    name = Path(filename).name
    if name != filename or not name:
        raise BadRequestException("Invalid certification image path")
    if any(ch in name for ch in ("/", "\\", "..")):
        raise BadRequestException("Invalid certification image path")
    return name


def _to_filename(certification_image_url: str) -> str | None:
    if not certification_image_url.startswith(CERT_IMAGE_PREFIX):
        return None
    return _safe_filename(certification_image_url.removeprefix(CERT_IMAGE_PREFIX))


def _signature(filename: str, expires: int) -> str:
    payload = f"{filename}:{expires}".encode("utf-8")
    return hmac.new(_secret(), payload, hashlib.sha256).hexdigest()


def sign_certification_image_url(
    certification_image_url: str | None,
    *,
    now: int | None = None,
) -> str | None:
    """Return a relative signed URL for locally stored certification images.

    External legacy URLs are deliberately not proxied/signed in Phase A because
    there is no verified storage backend ownership. They remain hidden from the
    admin detail response until migrated or re-uploaded via the admin endpoint.
    """
    if not certification_image_url:
        return None
    filename = _to_filename(certification_image_url)
    if filename is None:
        return None
    issued_at = int(time.time() if now is None else now)
    expires = issued_at + SIGNED_URL_TTL_SECONDS
    sig = _signature(filename, expires)
    return (
        f"/api/v1/admin/companions/certification-images/{filename}"
        f"?expires={expires}&sig={sig}"
    )


def verify_signed_certification_image(filename: str, expires: int, sig: str) -> Path:
    safe_name = _safe_filename(filename)
    if expires < int(time.time()):
        raise ForbiddenException("Certification image URL expired")
    expected = _signature(safe_name, expires)
    if not hmac.compare_digest(expected, sig):
        raise ForbiddenException("Invalid certification image signature")

    path = (CERT_IMAGE_DIR / safe_name).resolve()
    root = CERT_IMAGE_DIR.resolve()
    if root not in path.parents and path != root:
        raise ForbiddenException("Invalid certification image path")
    if not path.exists() or not path.is_file():
        raise NotFoundException("Certification image not found")
    return path


async def save_certification_image(file: UploadFile) -> str:
    if file.content_type not in ALLOWED_CERT_IMAGE_TYPES:
        raise UnsupportedMediaTypeException(
            "Invalid file type. Only jpg/jpeg/png/webp are allowed"
        )

    content = await file.read()
    if len(content) > MAX_CERT_IMAGE_SIZE:
        raise PayloadTooLargeException("File too large. Maximum size is 5MB")

    ext = ALLOWED_CERT_IMAGE_TYPES[file.content_type]
    filename = f"{uuid.uuid4().hex}{ext}"
    CERT_IMAGE_DIR.mkdir(parents=True, exist_ok=True)
    (CERT_IMAGE_DIR / filename).write_bytes(content)
    return f"{CERT_IMAGE_PREFIX}{filename}"


def content_type_for(path: Path) -> str:
    return mimetypes.guess_type(path.name)[0] or "application/octet-stream"
