#!/usr/bin/env python3
"""
design/generate.py — read tokens.json and emit:
  - wechat/styles/tokens.wxss   (CSS variables)
  - wechat/utils/tokens.js      (JS constants)

iOS DesignSystem.swift is NOT auto-generated (handwritten to avoid Xcode
project churn). Run after every edit to tokens.json.

Usage:
    python design/generate.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOKENS = ROOT / "design" / "tokens.json"
WXSS_OUT = ROOT / "wechat" / "styles" / "tokens.wxss"
JS_OUT = ROOT / "wechat" / "utils" / "tokens.js"

HEADER_AUTO = (
    "/* AUTO-GENERATED by design/generate.py — DO NOT EDIT BY HAND.\n"
    " * Source of truth: design/tokens.json\n"
    " */\n\n"
)


def kebab(name: str) -> str:
    return name.replace("_", "-")


def emit_wxss(tokens: dict) -> str:
    lines: list[str] = [HEADER_AUTO, "page {\n"]

    def section(title: str) -> None:
        lines.append(f"  /* ---- {title} ---- */\n")

    # Spacing
    section("Spacing (8rpx grid, 1pt=2rpx)")
    for k, v in tokens["spacing"].items():
        lines.append(f"  --spacing-{kebab(k)}: {v['rpx']}rpx;\n")

    # Radius
    section("Radius")
    for k, v in tokens["radius"].items():
        lines.append(f"  --radius-{kebab(k)}: {v['rpx']}rpx;\n")

    # Tap area
    section("Tap area (iOS HIG)")
    for k, v in tokens["tap_area"].items():
        lines.append(f"  --tap-{kebab(k)}: {v['rpx']}rpx;\n")

    # Typography
    section("Typography")
    for k, v in tokens["typography"].items():
        lines.append(f"  --font-size-{kebab(k)}: {v['rpx']}rpx;\n")
    for k, v in tokens["typography"].items():
        lines.append(f"  --font-weight-{kebab(k)}: {v['weight']};\n")

    # Line height
    section("Line height")
    for k, v in tokens["line_height"].items():
        lines.append(f"  --line-height-{kebab(k)}: {v};\n")

    # Components
    section("Components")
    for comp_name, comp in tokens["components"].items():
        for prop, v in comp.items():
            lines.append(
                f"  --{kebab(comp_name)}-{kebab(prop)}: {v['rpx']}rpx;\n"
            )

    # Color
    section("Color")
    for k, v in tokens["color"].items():
        lines.append(f"  --color-{kebab(k)}: {v};\n")

    # Shadow
    section("Shadow")
    for k, v in tokens["shadow"].items():
        lines.append(f"  --shadow-{kebab(k)}: {v};\n")

    # Motion
    section("Motion")
    for k, v in tokens["motion"].items():
        lines.append(f"  --{kebab(k)}: {v};\n")

    # Z-index
    section("Z-index")
    for k, v in tokens["z_index"].items():
        lines.append(f"  --z-{kebab(k)}: {v};\n")

    lines.append("}\n")
    return "".join(lines)


def emit_js(tokens: dict) -> str:
    lines: list[str] = [
        "// AUTO-GENERATED by design/generate.py — DO NOT EDIT BY HAND.\n",
        "// Source of truth: design/tokens.json\n",
        "//\n",
        "// 用法（小程序 JS 端）：\n",
        "//   const { spacing, components, color } = require('../../utils/tokens.js');\n",
        "//   const padding = spacing.lg.rpx;  // 32\n",
        "\n",
        "module.exports = ",
    ]
    payload = {
        "version": tokens.get("version"),
        "spacing": tokens["spacing"],
        "radius": tokens["radius"],
        "tapArea": tokens["tap_area"],
        "typography": tokens["typography"],
        "lineHeight": tokens["line_height"],
        "components": tokens["components"],
        "color": tokens["color"],
        "shadow": tokens["shadow"],
        "motion": tokens["motion"],
        "zIndex": tokens["z_index"],
    }
    lines.append(json.dumps(payload, indent=2, ensure_ascii=False))
    lines.append(";\n")
    return "".join(lines)


def main() -> int:
    if not TOKENS.exists():
        print(f"[generate.py] missing {TOKENS}", file=sys.stderr)
        return 1
    tokens = json.loads(TOKENS.read_text(encoding="utf-8"))

    WXSS_OUT.parent.mkdir(parents=True, exist_ok=True)
    JS_OUT.parent.mkdir(parents=True, exist_ok=True)

    WXSS_OUT.write_text(emit_wxss(tokens), encoding="utf-8")
    JS_OUT.write_text(emit_js(tokens), encoding="utf-8")

    print(f"[generate.py] wrote {WXSS_OUT.relative_to(ROOT)}")
    print(f"[generate.py] wrote {JS_OUT.relative_to(ROOT)}")
    print("[generate.py] reminder: hand-sync ios/YiLuAn/Core/Extensions/DesignSystem.swift")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
