"""add_service_types_to_companion_profile

Revision ID: 2efb4290575a
Revises: a1b2c3d4e5f6
Create Date: 2026-04-05 11:12:59.895227
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2efb4290575a'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companion_profiles', sa.Column('service_types', sa.String(length=200), nullable=True))
    # Backfill: existing companions default to all service types
    op.execute("UPDATE companion_profiles SET service_types = 'full_accompany,half_accompany,errand' WHERE service_types IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companion_profiles', 'service_types')
    # ### end Alembic commands ###
