"""add service_contracts table + contract_status ENUM + immutable_fields trigger

(S3-DEV-001-CONTRACT-DOMAIN)

Revision ID: d5e6f7a8b9c1
Revises: c4d5e6f7a8b9
Create Date: 2026-06-06 14:16:43.617483

ADR-0047 §3.1 完整 schema + ADR-0046 §3.3 第 3 层 WORM 防御 (DB trigger):
- contract_status ENUM 6 状态
- service_contracts 表 (一单一合同 UNIQUE order_id + contract_hash UNIQUE)
- partial index ``idx_service_contracts_compensation`` on
  (status, retry_count, updated_at) WHERE status IN
  ('pending_generation', 'generation_failed') — compensation cron 只扫
  待补偿行,不扫全表
- immutable_fields_guard BEFORE UPDATE trigger (PL/pgSQL, 拒 8 immutable
  字段改动 — order_id / template_version / contract_hash / hash_inputs /
  storage_blob_path (once set) / generated_at (once set) / is_immutable /
  created_at)
- orders.contract_id nullable FK use_alter=True (S3 启动后新订单, 不回填历史;
  use_alter 防 service_contracts ←→ orders 循环 FK 在 create_all 时崩)

# Down_revision rationale (胡桃 2026-06-06)

本 migration 并行于 S3-DEV-001-INSURANCE-DOMAIN (魈裁 ``d5e6f7a8b9c0``,
PR #199)。两者都接在 ``c4d5e6f7a8b9`` 上, 避免串行依赖 —
``orders.insurance_id`` (INSURANCE 加) 与 ``orders.contract_id`` (本 PR 加)
是独立列, 零列名冲突。谁先合 main 谁拿 head; 后合者 rebase main 时只需
改 ``down_revision`` 接在对方 revision 后, 本 migration 逻辑零改动,
不需额外 merge migration。

# Migration body

骨架由 ``alembic revision --autogenerate`` 产生 (model 是 ground truth)。
手工补 1 块 autogen 不会出的 DDL:
- ``service_contracts_immutable_guard`` PL/pgSQL trigger + function
  (autogen 不出 trigger; SQLite 由 ContractStateMachine + ORM @validates
  在 app 层 enforce, 无需 trigger)
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5e6f7a8b9c1"
down_revision: Union[str, None] = "c4d5e6f7a8b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ---------------------------------------------------------------------------
# Immutable trigger DDL (PG only — SQLite has no PL/pgSQL)
#
# AC#2 字面 (魈 08:25): 8 immutable 字段。不包含 ``id`` — PK 由 DB 物理
# immutable 兜底, 不在应用层 trigger 重复 guard。
#
# Field list 必须与 ``app/models/service_contract.py::IMMUTABLE_FIELDS``
# 一致; 漂移由 ``test_contract_state_machine.py::TestImmutableFieldsSentinel``
# fail-fast。
# ---------------------------------------------------------------------------

_TRIGGER_BODY_SQL = """
CREATE OR REPLACE FUNCTION service_contracts_immutable_guard()
RETURNS TRIGGER AS $$
BEGIN
    IF (OLD.order_id IS DISTINCT FROM NEW.order_id) THEN
        RAISE EXCEPTION 'service_contracts.order_id is immutable (ADR-0046 §3.3 layer 3)';
    END IF;
    IF (OLD.template_version IS DISTINCT FROM NEW.template_version) THEN
        RAISE EXCEPTION 'service_contracts.template_version is immutable';
    END IF;
    IF (OLD.contract_hash IS DISTINCT FROM NEW.contract_hash) THEN
        RAISE EXCEPTION 'service_contracts.contract_hash is immutable';
    END IF;
    IF (OLD.hash_inputs IS DISTINCT FROM NEW.hash_inputs) THEN
        RAISE EXCEPTION 'service_contracts.hash_inputs is immutable';
    END IF;
    -- storage_blob_path: NULL → non-NULL allowed (first write); non-NULL → other rejected
    IF (OLD.storage_blob_path IS NOT NULL
        AND OLD.storage_blob_path IS DISTINCT FROM NEW.storage_blob_path) THEN
        RAISE EXCEPTION 'service_contracts.storage_blob_path is immutable once set';
    END IF;
    -- generated_at: NULL → non-NULL allowed (first generation); non-NULL → other rejected
    IF (OLD.generated_at IS NOT NULL
        AND OLD.generated_at IS DISTINCT FROM NEW.generated_at) THEN
        RAISE EXCEPTION 'service_contracts.generated_at is immutable once set';
    END IF;
    IF (OLD.is_immutable IS DISTINCT FROM NEW.is_immutable) THEN
        RAISE EXCEPTION 'service_contracts.is_immutable cannot be flipped';
    END IF;
    IF (OLD.created_at IS DISTINCT FROM NEW.created_at) THEN
        RAISE EXCEPTION 'service_contracts.created_at is immutable';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

_CREATE_TRIGGER_SQL = """
CREATE TRIGGER service_contracts_immutable_guard_trigger
    BEFORE UPDATE ON service_contracts
    FOR EACH ROW
    EXECUTE FUNCTION service_contracts_immutable_guard();
"""

_DROP_TRIGGER_SQL = (
    "DROP TRIGGER IF EXISTS service_contracts_immutable_guard_trigger "
    "ON service_contracts;"
)
_DROP_TRIGGER_FN_SQL = "DROP FUNCTION IF EXISTS service_contracts_immutable_guard();"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_contracts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "order_id",
            sa.Uuid(),
            nullable=False,
            comment="一单一合同 UNIQUE (ADR-0047 §3.1, immutable)",
        ),
        sa.Column(
            "template_version",
            sa.String(length=32),
            nullable=False,
            comment="合同模板 semver, 如 'v1.0.0'; 入 hash_inputs (immutable)",
        ),
        sa.Column(
            "contract_hash",
            sa.String(length=64),
            nullable=False,
            comment="SHA-256 hex 64-char, ADR-0046 §3.2 公式; UNIQUE 防双写 (immutable)",
        ),
        sa.Column(
            "hash_inputs",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
            comment="ADR-0046 §3.2 hash 原材料 snapshot, 一次性冻结 (immutable)",
        ),
        sa.Column(
            "storage_blob_path",
            sa.String(length=512),
            nullable=True,
            comment="contracts/{YYYY}/{MM}/{order_id}_{hash}.pdf; pending 时 NULL (immutable 一旦写入)",  # noqa: E501
        ),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="status=active 时设; 后续 immutable (审计)",
        ),
        sa.Column(
            "is_immutable",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="WORM 标记本身不可关 (ADR-0046 §3.3 第 3 层)",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending_generation",
                "generating",
                "active",
                "generation_failed",
                "generation_permanently_failed",
                "manually_invalidated",
                name="contract_status",
            ),
            server_default="pending_generation",
            nullable=False,
            comment="ContractStateMachine 维护; 6 状态; 直接 UPDATE 禁",
        ),
        sa.Column(
            "retry_count",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="补偿 cron retry 次数 (5min/30min/2h 三档, 上限 3 → permanently_failed)",
        ),
        sa.Column(
            "last_error_trace",
            sa.Text(),
            nullable=True,
            comment="最近一次失败的 error trace; 补偿 cron 写入",
        ),
        sa.Column(
            "invalidation_reason",
            sa.Text(),
            nullable=True,
            comment="作废原因; status=manually_invalidated 时**必填**",
        ),
        sa.Column(
            "invalidated_by_admin_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
            comment=(
                "作废人 admin_user_id (BigInt PG / Int SQLite); "
                "status=manually_invalidated 时**必填**"
            ),
        ),
        sa.Column(
            "invalidated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="作废时间",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="行创建时间; immutable",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="行更新时间; 自动维护",
        ),
        sa.ForeignKeyConstraint(["invalidated_by_admin_id"], ["admin_users.id"]),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_service_contracts_compensation",
        "service_contracts",
        ["status", "retry_count", "updated_at"],
        unique=False,
        postgresql_where=sa.text(
            "status IN ('pending_generation', 'generation_failed')"
        ),
    )
    op.create_index(
        op.f("ix_service_contracts_contract_hash"),
        "service_contracts",
        ["contract_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_service_contracts_order_id"),
        "service_contracts",
        ["order_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_service_contracts_status"),
        "service_contracts",
        ["status"],
        unique=False,
    )
    op.add_column(
        "orders",
        sa.Column(
            "contract_id",
            sa.Uuid(),
            nullable=True,
            comment="一单一合同 nullable (PRD-003 §AC-5); use_alter 防循环 FK",
        ),
    )
    op.create_foreign_key(
        "fk_orders_contract_id",
        "orders",
        "service_contracts",
        ["contract_id"],
        ["id"],
        use_alter=True,
    )
    # ### end Alembic commands ###

    # ----- Manual additions (autogen does not produce these) -----
    # PL/pgSQL trigger for immutable-field guard (ADR-0046 §3.3 layer 3).
    # SQLite has no PL/pgSQL — application-layer ContractStateMachine + ORM
    # @validates carry the guard there.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute(_TRIGGER_BODY_SQL)
        op.execute(_CREATE_TRIGGER_SQL)


def downgrade() -> None:
    bind = op.get_bind()

    # Reverse manual addition first (trigger + function).
    if bind.dialect.name == "postgresql":
        op.execute(_DROP_TRIGGER_SQL)
        op.execute(_DROP_TRIGGER_FN_SQL)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_orders_contract_id", "orders", type_="foreignkey")
    op.drop_column("orders", "contract_id")
    op.drop_index(op.f("ix_service_contracts_status"), table_name="service_contracts")
    op.drop_index(op.f("ix_service_contracts_order_id"), table_name="service_contracts")
    op.drop_index(
        op.f("ix_service_contracts_contract_hash"), table_name="service_contracts"
    )
    op.drop_index(
        "idx_service_contracts_compensation",
        table_name="service_contracts",
        postgresql_where=sa.text(
            "status IN ('pending_generation', 'generation_failed')"
        ),
    )
    op.drop_table("service_contracts")
    # ### end Alembic commands ###

    # Drop ENUM type after the column using it is gone.
    if bind.dialect.name == "postgresql":
        sa.Enum(
            "pending_generation",
            "generating",
            "active",
            "generation_failed",
            "generation_permanently_failed",
            "manually_invalidated",
            name="contract_status",
        ).drop(bind, checkfirst=True)
