apiVersion: v1
kind: Service
metadata:
  name: {{ include "yiluan.fullname" . }}-api
  labels:
    {{- include "yiluan.componentLabels" (dict "ctx" . "component" "api") | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "yiluan.componentSelectorLabels" (dict "ctx" . "component" "api") | nindent 4 }}
