{{- if .Values.redis.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "yiluan.fullname" . }}-redis
  labels:
    {{- include "yiluan.componentLabels" (dict "ctx" . "component" "redis") | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 6379
      name: redis
    {{- if .Values.redis.sentinel.enabled }}
    - port: 26379
      name: sentinel
    {{- end }}
  selector:
    {{- include "yiluan.componentSelectorLabels" (dict "ctx" . "component" "redis") | nindent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "yiluan.fullname" . }}-redis
  labels:
    {{- include "yiluan.componentLabels" (dict "ctx" . "component" "redis") | nindent 4 }}
spec:
  serviceName: {{ include "yiluan.fullname" . }}-redis
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      {{- include "yiluan.componentSelectorLabels" (dict "ctx" . "component" "redis") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "yiluan.componentSelectorLabels" (dict "ctx" . "component" "redis") | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          command: ["redis-server", "--appendonly", "yes"]
          ports:
            - containerPort: 6379
              name: redis
          {{- if .Values.redis.auth.existingSecret }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.auth.existingSecret }}
                  key: redis-password
          {{- end }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
        {{- if .Values.redis.sentinel.enabled }}
        - name: sentinel
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          command: ["redis-sentinel", "/etc/redis/sentinel.conf"]
          ports:
            - containerPort: 26379
              name: sentinel
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
        {{- end }}
{{- end }}
