// AUTO-GENERATED by design/generate.py — DO NOT EDIT BY HAND.
// Source of truth: design/tokens.json
//
// 用法（小程序 JS 端）：
//   const { spacing, components, color } = require('../../utils/tokens.js');
//   const padding = spacing.lg.rpx;  // 32

module.exports = {
  "version": "1.0.0",
  "spacing": {
    "xxs": {
      "pt": 2,
      "rpx": 4
    },
    "xs": {
      "pt": 4,
      "rpx": 8
    },
    "sm": {
      "pt": 8,
      "rpx": 16
    },
    "md": {
      "pt": 12,
      "rpx": 24
    },
    "lg": {
      "pt": 16,
      "rpx": 32
    },
    "xl": {
      "pt": 24,
      "rpx": 48
    },
    "xxl": {
      "pt": 32,
      "rpx": 64
    },
    "xxxl": {
      "pt": 48,
      "rpx": 96
    }
  },
  "radius": {
    "xs": {
      "pt": 2,
      "rpx": 4
    },
    "sm": {
      "pt": 4,
      "rpx": 8
    },
    "md": {
      "pt": 8,
      "rpx": 16
    },
    "lg": {
      "pt": 12,
      "rpx": 24
    },
    "xl": {
      "pt": 16,
      "rpx": 32
    },
    "full": {
      "pt": 9999,
      "rpx": 9999
    }
  },
  "tapArea": {
    "min": {
      "pt": 44,
      "rpx": 88,
      "note": "iOS HIG minimum tappable area"
    }
  },
  "typography": {
    "small": {
      "pt": 10,
      "rpx": 20,
      "weight": "regular",
      "ios_name": "dsSmall"
    },
    "caption": {
      "pt": 12,
      "rpx": 24,
      "weight": "regular",
      "ios_name": "dsCaption"
    },
    "body": {
      "pt": 14,
      "rpx": 28,
      "weight": "regular",
      "ios_name": "dsBody"
    },
    "headline": {
      "pt": 15,
      "rpx": 30,
      "weight": "semibold",
      "ios_name": "dsHeadline"
    },
    "title": {
      "pt": 16,
      "rpx": 32,
      "weight": "bold",
      "ios_name": "dsTitle"
    },
    "h1": {
      "pt": 18,
      "rpx": 36,
      "weight": "bold",
      "ios_name": "dsH1"
    },
    "hero": {
      "pt": 24,
      "rpx": 48,
      "weight": "bold",
      "ios_name": "dsHero"
    }
  },
  "lineHeight": {
    "tight": 1.3,
    "normal": 1.5,
    "relaxed": 1.7
  },
  "components": {
    "button": {
      "height_primary": {
        "pt": 48,
        "rpx": 96,
        "note": "AI-10 决议：跨端统一主按钮 48pt"
      },
      "height_secondary": {
        "pt": 40,
        "rpx": 80
      },
      "height_small": {
        "pt": 32,
        "rpx": 64
      },
      "radius": {
        "pt": 8,
        "rpx": 16
      },
      "padding_h": {
        "pt": 16,
        "rpx": 32
      }
    },
    "navbar": {
      "height": {
        "pt": 44,
        "rpx": 88,
        "note": "AI-10 决议：iOS HIG nav bar 44pt；小程序之前 88rpx 已对齐"
      },
      "padding_h": {
        "pt": 16,
        "rpx": 32
      }
    },
    "tabbar": {
      "height": {
        "pt": 49,
        "rpx": 98
      }
    },
    "card": {
      "padding": {
        "pt": 16,
        "rpx": 32
      },
      "radius": {
        "pt": 12,
        "rpx": 24
      },
      "gap": {
        "pt": 12,
        "rpx": 24
      }
    },
    "input": {
      "height": {
        "pt": 44,
        "rpx": 88
      },
      "radius": {
        "pt": 8,
        "rpx": 16
      },
      "padding_h": {
        "pt": 12,
        "rpx": 24
      }
    },
    "list_item": {
      "height_min": {
        "pt": 56,
        "rpx": 112
      },
      "padding_h": {
        "pt": 16,
        "rpx": 32
      },
      "padding_v": {
        "pt": 12,
        "rpx": 24
      }
    }
  },
  "color": {
    "brand": "#1890FF",
    "brand_dark": "#096DD9",
    "brand_light": "#E6F7FF",
    "brand_lighter": "#BAE7FF",
    "secondary": "#722ED1",
    "accent": "#FF7A45",
    "success": "#52C41A",
    "success_light": "#F6FFED",
    "warning": "#FAAD14",
    "warning_light": "#FFFBE6",
    "danger": "#FF4D4F",
    "danger_light": "#FFF2F0",
    "info": "#1890FF",
    "info_light": "#E6F7FF",
    "text_primary": "#1F2937",
    "text_secondary": "#6B7280",
    "text_hint": "#9CA3AF",
    "text_disabled": "#D1D5DB",
    "text_white": "#FFFFFF",
    "text_link": "#1890FF",
    "bg_page": "#F7F8FA",
    "bg_card": "#FFFFFF",
    "bg_input": "#F9FAFB",
    "bg_hover": "#F3F4F6",
    "bg_skeleton": "#E5E7EB",
    "bg_mask": "rgba(0, 0, 0, 0.45)",
    "border": "#E5E7EB",
    "border_light": "#F3F4F6",
    "border_input": "#D1D5DB",
    "border_focus": "#1890FF"
  },
  "shadow": {
    "xs": "0 1rpx 4rpx rgba(0, 0, 0, 0.03)",
    "sm": "0 2rpx 8rpx rgba(0, 0, 0, 0.05)",
    "md": "0 4rpx 16rpx rgba(0, 0, 0, 0.08)",
    "lg": "0 8rpx 32rpx rgba(0, 0, 0, 0.12)",
    "xl": "0 16rpx 48rpx rgba(0, 0, 0, 0.16)"
  },
  "motion": {
    "duration_fast": "150ms",
    "duration_normal": "300ms",
    "duration_slow": "500ms",
    "ease_in_out": "cubic-bezier(0.4, 0, 0.2, 1)",
    "ease_out": "cubic-bezier(0, 0, 0.2, 1)",
    "ease_spring": "cubic-bezier(0.34, 1.56, 0.64, 1)"
  },
  "zIndex": {
    "sticky": 100,
    "fixed": 200,
    "modal": 300,
    "toast": 400
  }
};
